# -*- coding: utf-8 -*-
"""yolov2-ultimate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izaYy2vRiSF9MboRb8ovPiEVQ_BNLYM7
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %%writefile hyp_trash.yaml
# lr0: 0.012
# lrf: 0.2
# momentum: 0.937
# weight_decay: 0.0005
# warmup_epochs: 3.0
# warmup_momentum: 0.8
# warmup_bias_lr: 0.1
# box: 0.05
# cls: 0.5
# cls_pw: 1.0
# obj: 1.5
# obj_pw: 1.0
# iou_t: 0.15
# anchor_t: 4.0
# fl_gamma: 0.0
# hsv_h: 0.0
# hsv_s: 0.0
# hsv_v: 0.0
# degrees: 0.0
# translate: 0.0
# scale: 0.0
# shear: 0.0
# perspective: 0.0
# flipud: 0.0
# fliplr: 0.0
# mosaic: 0.5
# mixup: 0.0
# copy_paste: 0.0
# label_smoothing: 0.1
# nbs: 64

!python train.py --img 640 --batch 32 --epochs 40 --data trash-ai-v6-4/data.yaml --weights yolov5s.pt --name trash_ai_v6 --cache --hyp hyp_trash.yaml
