# -*- coding: utf-8 -*-
"""yolov2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ER_zDrBPuae9ke-R5dpIMNT0tYZFwHv0
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="7ivCMKxGSkZNYjDJQ16r")
project = rf.workspace("trash-ai-27vay").project("trash-ai-v2")
version = project.version(1)
dataset = version.download("yolov5")

!python train.py --img 640 --batch 16 --epochs 36 --data Trash-AI-v2-1/data.yaml --weights yolov5s.pt --name trash_detector